# Developer: Shaik Riyaz
# Created for: CGI Munich

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(500, 400))
        AboutDialog.setMaximumSize(QtCore.QSize(500, 400))
        AboutDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        AboutDialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
        self.close_btn = QtWidgets.QPushButton(AboutDialog, clicked=lambda: AboutDialog.close())
        self.close_btn.setGeometry(QtCore.QRect(390, 360, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.line_4 = QtWidgets.QFrame(AboutDialog)
        self.line_4.setGeometry(QtCore.QRect(485, 5, 20, 390))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(AboutDialog)
        self.line_3.setGeometry(QtCore.QRect(-5, 5, 20, 388))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(AboutDialog)
        self.line_2.setGeometry(QtCore.QRect(5, 385, 488, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(AboutDialog)
        self.line.setGeometry(QtCore.QRect(5, -5, 488, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.info_lbl = QtWidgets.QLabel(AboutDialog)
        self.info_lbl.setEnabled(True)
        self.info_lbl.setGeometry(QtCore.QRect(10, 10, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_lbl.sizePolicy().hasHeightForWidth())
        self.info_lbl.setSizePolicy(sizePolicy)
        self.info_lbl.setMinimumSize(QtCore.QSize(480, 150))
        self.info_lbl.setMaximumSize(QtCore.QSize(480, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.info_lbl.setFont(font)
        self.info_lbl.setWordWrap(True)
        self.info_lbl.setObjectName("info_lbl")
        self.label = QtWidgets.QLabel(AboutDialog)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 250, 480, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(480, 100))
        self.label.setMaximumSize(QtCore.QSize(480, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.close_btn.setText(_translate("AboutDialog", "Close"))
        self.info_lbl.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#550000;\">About</span></p><p align=\"center\"><br/></p><p><span style=\" font-size:10pt; color:#000000;\">This is a properatory software application developed solely for General Consulate of India Munich to handel financial statistics.</span></p></body></html>"))
        self.label.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#003207;\">Developed By: Munich Intelligence</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#003207;\">Developer: Shaik Riyaz</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    ui = Ui_AboutDialog()
    ui.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())
