# Developer: Shaik Riyaz
# Created for: CGI Munich

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VersionDialog(object):
    def setupUi(self, VersionDialog):
        VersionDialog.setObjectName("VersionDialog")
        VersionDialog.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VersionDialog.sizePolicy().hasHeightForWidth())
        VersionDialog.setSizePolicy(sizePolicy)
        VersionDialog.setMinimumSize(QtCore.QSize(500, 300))
        VersionDialog.setMaximumSize(QtCore.QSize(500, 300))
        VersionDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        VersionDialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
        self.close_btn = QtWidgets.QPushButton(VersionDialog, clicked=lambda: VersionDialog.close())
        self.close_btn.setGeometry(QtCore.QRect(390, 260, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.line = QtWidgets.QFrame(VersionDialog)
        self.line.setGeometry(QtCore.QRect(5, -5, 488, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verinfo_lbl = QtWidgets.QLabel(VersionDialog)
        self.verinfo_lbl.setEnabled(False)
        self.verinfo_lbl.setGeometry(QtCore.QRect(10, 10, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verinfo_lbl.sizePolicy().hasHeightForWidth())
        self.verinfo_lbl.setSizePolicy(sizePolicy)
        self.verinfo_lbl.setMinimumSize(QtCore.QSize(480, 150))
        self.verinfo_lbl.setMaximumSize(QtCore.QSize(480, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.verinfo_lbl.setFont(font)
        self.verinfo_lbl.setWordWrap(True)
        self.verinfo_lbl.setObjectName("verinfo_lbl")
        self.line_3 = QtWidgets.QFrame(VersionDialog)
        self.line_3.setGeometry(QtCore.QRect(-5, 5, 20, 290))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(VersionDialog)
        self.line_4.setGeometry(QtCore.QRect(485, 5, 20, 290))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(VersionDialog)
        self.line_2.setGeometry(QtCore.QRect(5, 285, 488, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.link_lbl = QtWidgets.QLabel(VersionDialog)
        self.link_lbl.setGeometry(QtCore.QRect(10, 180, 480, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_lbl.sizePolicy().hasHeightForWidth())
        self.link_lbl.setSizePolicy(sizePolicy)
        self.link_lbl.setMinimumSize(QtCore.QSize(480, 50))
        self.link_lbl.setMaximumSize(QtCore.QSize(480, 50))
        self.link_lbl.setOpenExternalLinks(True)
        self.link_lbl.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.link_lbl.setObjectName("link_lbl")

        self.retranslateUi(VersionDialog)
        QtCore.QMetaObject.connectSlotsByName(VersionDialog)

    def retranslateUi(self, VersionDialog):
        _translate = QtCore.QCoreApplication.translate
        VersionDialog.setWindowTitle(_translate("VersionDialog", "CGI Munich Version"))
        self.close_btn.setText(_translate("VersionDialog", "Close"))
        self.verinfo_lbl.setText(_translate("VersionDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#550000;\">Current Version: 1.0.3</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" color:#000000;\">Please find the latest version of the application in the below link.</span></p></body></html>"))
        self.link_lbl.setText(_translate("VersionDialog", "<a href=\"https://drive.google.com/drive/folders/1pIS78hTQsQxMdfVICt-Ty3C_1377Kinw\">https://drive.google.com/drive/folders/1pIS78hTQsQxMdfVICt-Ty3C_1377Kinw/</a>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VersionDialog = QtWidgets.QDialog()
    ui = Ui_VersionDialog()
    ui.setupUi(VersionDialog)
    VersionDialog.show()
    sys.exit(app.exec_())
